/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_mitre_svmp_events_BaseServer */

#ifndef _Included_org_mitre_svmp_events_BaseServer
#define _Included_org_mitre_svmp_events_BaseServer
#ifdef __cplusplus
extern "C" {
#endif
#undef org_mitre_svmp_events_BaseServer_BUFFER_SIZE
#define org_mitre_svmp_events_BaseServer_BUFFER_SIZE 8192L


/*
 * Class:     org_mitre_svmp_events_BaseServer
 * Method:    InitSockClient
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_mitre_svmp_events_BaseServer_InitSockClient
  (JNIEnv *, jclass, jstring);

/*
 * Class:     org_mitre_svmp_events_BaseServer
 * Method:    SockClientWrite
 * Signature: (ILorg/mitre/svmp/protocol/SVMPSensorEventMessage;)I
 */
JNIEXPORT jint JNICALL Java_org_mitre_svmp_events_BaseServer_SockClientWrite
  (JNIEnv *, jclass, jint, jobject);

/*
 * Class:     org_mitre_svmp_events_BaseServer
 * Method:    SockClientClose
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_mitre_svmp_events_BaseServer_SockClientClose
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
